name: PR Checks
on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: |
          git fetch origin main:main
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Lint
        run: npm run lint
        
      - name: Check changeset
        run: |
          # Check if .changeset directory exists
          if [ ! -d ".changeset" ]; then
            echo "Creating .changeset directory"
            npx changeset init
          fi
          npx changeset status --since=main
        continue-on-error: true

